services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      DATABASE_URL: postgresql://postgres:1234@db:5432/postgres
      NODE_ENV: development
      PORT: 3000
    working_dir: /app
    volumes:
      - type: bind
        source: ./
        target: /app
      - /app/node_modules
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
    tty: true
    restart: unless-stopped

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: 1234
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 5

volumes:
  db_data:
