# Use postgres/example user/password credentials

services:
  db_desf5:
    image: postgres
    restart: always
    shm_size: 128mb

    environment:
      POSTGRES_PASSWORD: 1234
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
